### PR TITLE
Update community edition variables for 4.0.0

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Anyone able to look at this?

**Comment by SomeoneWeird** [comment]
I guess you missed this. Oh well :)

**Comment by tleyden** [comment]
@brianshumate is this a useful PR?

**Comment by brianshumate** [comment]
Hmm, watch fell off this repo and I have not been getting notifications.

I just added 4.0.0 community yesterday. I've made sure I am getting notifications for this repo now, sorry I missed this @SomeoneWeird. :(

**Comment by SomeoneWeird** [comment]
Yeah, I noticed you updated community to 4 anyway, which is why I closed this :+1:

**Pull request closed without merging**
